apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vegetaas
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.85"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: vegetaas
    image:
      name: vibioh/vegetaas
      tag: "202208060909" # {"$imagepolicy": "default:flux-vegetaas-api:tag"}
    config:
      VEGETAAS_LOGGER_JSON: "true"
      VEGATAAS_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: vegetaas
    autoscaling:
      enabled: false
    pprof:
      enabled: true
